site_name: Q-ETL Documentation
theme: material
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Basic Tutorial: basic_tutorial.md
  - Configuration: configurations.md
  - API:
    - Inputs: Inputs.md
    - Workers: workers.md
    - Constructors: constructors.md
    - Outputs: outputs.md
    - Integrations: integrations.md
    - Examples: examples.md
  - Help:
    - FAQ: faq.md
    - Troubleshooting: troubleshooting.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python: {}
